export type LeaderboardKey = 'HardEX' | 'EX' | 'ITG' | 'ITGRate' | 'EXRate';
export type PackLeaderboardDifficulty = 'medium' | 'hard' | 'challenge';

export type WidgetFeatureConfig =
  | { type: 'recentPlays'; leaderboards: LeaderboardKey[] }
  | {
      type: 'packLeaderboard';
      packId: number;
      packName: string;
      bannerUrl: string | null;
      difficulty: PackLeaderboardDifficulty;
      leaderboards: LeaderboardKey[];
    }
  | { type: 'currentSession' };

export interface WidgetConfig {
  version: 1;
  orientation: 'horizontal' | 'vertical';
  features: WidgetFeatureConfig[];
  /**
   * Hide the alias/avatar header band above the feature panels. Every widget URL generated by the
   * wizard now sets this; it's optional (rather than a new config version) purely so the URLs
   * streamers already have in OBS - which predate the field - keep rendering exactly as before,
   * header and all, with the same pixel dimensions they were sized for.
   */
  hideProfile?: boolean;
}

export const PANEL_WIDTH = 300;
export const PANEL_HEIGHT = 240;

// Height of the alias/avatar header band - only rendered for legacy configs without hideProfile
export const PROFILE_HEADER_H = 48;

// Compact heights for vertical orientation strips
export const COMPACT_HEIGHTS: Record<WidgetFeatureConfig['type'], number> = {
  recentPlays: 144,
  packLeaderboard: 80,
  currentSession: 80,
};

// Panel widths for horizontal orientation
export const HORIZONTAL_WIDTHS: Record<WidgetFeatureConfig['type'], number> = {
  recentPlays: 300,
  packLeaderboard: 235,
  currentSession: 220,
};

// Mirrors ELIGIBLE_PACK_IDS / PACK_LEADERBOARD_DIFFICULTY_OVERRIDES in api/src/utils/pack-leaderboard.ts -
// keep the two in sync.

/** Tech Heavy Charts 4. Hard/Expert-only leaderboards - see PACK_LEADERBOARD_DIFFICULTY_OVERRIDES. */
export const THC4_PACK_ID = 0; // TODO: set once the pack exists in the DB

export const ELIGIBLE_PACK_IDS = [101, 102, 131, 346, 348, 371, 380, THC4_PACK_ID];

export const PACK_LEADERBOARD_DIFFICULTIES: readonly PackLeaderboardDifficulty[] = ['medium', 'hard', 'challenge'];

/** Packs whose leaderboards only cover a subset of the difficulty slots; every other pack gets all three. */
export const PACK_LEADERBOARD_DIFFICULTY_OVERRIDES: Record<number, readonly PackLeaderboardDifficulty[]> = {
  [THC4_PACK_ID]: ['hard', 'challenge'],
};

/** The difficulty slots a given pack's leaderboards cover. */
export function getPackLeaderboardDifficulties(packId: number): readonly PackLeaderboardDifficulty[] {
  return PACK_LEADERBOARD_DIFFICULTY_OVERRIDES[packId] ?? PACK_LEADERBOARD_DIFFICULTIES;
}

export function encodeWidgetConfig(config: WidgetConfig): string {
  return btoa(JSON.stringify(config));
}

export function decodeWidgetConfig(encoded: string): WidgetConfig | null {
  try {
    return JSON.parse(atob(encoded)) as WidgetConfig;
  } catch {
    return null;
  }
}

export function getWidgetDimensions(config: WidgetConfig): { width: number; height: number } {
  // Filter out legacy 'profile' type from old encoded configs
  const features = config.features.filter((f) => (f as any).type !== 'profile');
  const headerH = config.hideProfile ? 0 : PROFILE_HEADER_H;

  if (config.orientation === 'horizontal') {
    const width = features.reduce((sum, f) => sum + (HORIZONTAL_WIDTHS[f.type] ?? 0), 0) || PANEL_WIDTH;
    return { width, height: PANEL_HEIGHT + headerH };
  }
  const height = features.reduce((sum, f) => sum + (COMPACT_HEIGHTS[f.type] ?? 0), 0) || PANEL_HEIGHT;
  return { width: PANEL_WIDTH, height: height + headerH };
}
